#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Nov 15 21:54:01 EET 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
